//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEGP_PROJECTNEWWW.Theme.unify {
    
    
    public partial class _2page_RA_allocation {
    }
}
